[package]
name = "plx"
description = "Practice programming exos in a delightful Learning eXperience"
homepage = "https://github.com/plx-pdg/plx"
repository = "https://github.com/plx-pdg/plx"
license-file = "LICENSE"
readme = false
version = "0.1.2"
edition = "2021"
exclude = ["*.md"]

[dependencies]
rand = "0.8.5"
notify = "6.1.1"
env_logger = "0.11.5"
log = "0.4.22"
tempfile = "3.12.0"