name = 'Make it not crash !!'
instruction = 'This programs crash, read it and fix it !'
[[checks]]
name = 'All lines are printed and no crash'
type = "output"
output = '''
Make it not crash !
ptr[0] = 2
ptr[1] = 3
ptr[2] = 4
new ptr = 3
'''
