name = 'Parse a DY basic exo'
instruction = 'Given an exo in raw DY syntax, implement parsing the name and solution.'
[[checks]]
name = ''
args = ["Joe", "5"]
type = "output"
output = 'The dog is Joe and has 5 legs'
