name: Tag on Version Change

on:
  push:
    branches: ["main"]


permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get the current version
        id: get_version
        run: |
          VERSION=v$(cat Cargo.toml | grep version | grep -o -P "\d+\.\d+\.\d+")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tag
        if: ${{env.VERSION != env.LATEST_TAG}}
        id: tag
        run: |
          git tag ${{VERSION}}
          git push origin ${{VERSION}}

